// Deutsch. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let de: [String: String] = [
        "about": "Über BeeHan Brightness",
        "access": "Zugriff auf Bedienungshilfen erlauben…",
        "applications_only": "BeeHan Brightness aktualisiert sich nur, wenn es aus dem Ordner „Programme“ läuft.",
        "auto": "Automatisch suchen",
        "available": "BeeHan Brightness {version} ist verfügbar",
        "by": "Von",
        "cancel": "Abbrechen",
        "check": "Nach Updates suchen…",
        "check_connection": "Prüfe deine Verbindung und versuche es erneut.",
        "check_failed": "Suche nach Updates fehlgeschlagen",
        "checking_signature": "Signatur wird geprüft…",
        "click_to_update": "Du hast {version}. Zum Aktualisieren klicken.",
        "daily": "Täglich",
        "dock": "Im Dock behalten",
        "download": "Download",
        "download_failed": "Der Download ist fehlgeschlagen.",
        "downloading": "Version {version} wird geladen…",
        "install_now": "Version {version} jetzt installieren",
        "installed": "Version {version} ist installiert.",
        "installing": "Wird installiert…",
        "language": "Sprache",
        "later": "Später",
        "login": "Beim Anmelden starten",
        "never": "Nie",
        "newest": "BeeHan Brightness {version} ist die neueste verfügbare Version.",
        "not_signed": "Der Download ist nicht von Zolfer Figueiredo signiert.",
        "now_using": "Du verwendest jetzt BeeHan Brightness {version}, die neueste verfügbare Version.",
        "ok": "OK",
        "quit": "BeeHan Brightness beenden",
        "reopen": "Neu öffnen",
        "reopen_failed": "Neu öffnen fehlgeschlagen: {error} Beende die App und öffne sie selbst.",
        "tool_failed": "{tool} fehlgeschlagen ({code}).",
        "up_to_date": "Du bist auf dem neuesten Stand!",
        "update_available": "Update verfügbar!",
        "update_complete": "Update abgeschlossen!",
        "update_failed": "Update konnte nicht installiert werden",
        "update_now": "Jetzt installieren",
        "update_question": "Du hast {version}. Jetzt aktualisieren?",
        "updating_to": "BeeHan Brightness wird auf {version} aktualisiert",
        "version": "Version {version}",
        "website": "Website",
        "weekly": "Wöchentlich",
        "wrong_download": "Der Download ist nicht BeeHan Brightness {version}.",
    ]
}
