// English. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let en: [String: String] = [
        "about": "About BeeHan Brightness",
        "access": "Allow Accessibility access…",
        "applications_only": "BeeHan Brightness updates itself only when it runs from the Applications folder.",
        "auto": "Check automatically",
        "available": "BeeHan Brightness {version} is available",
        "by": "By",
        "cancel": "Cancel",
        "check": "Check for updates…",
        "check_connection": "Check your connection and try again.",
        "check_failed": "Couldn’t check for updates",
        "checking_signature": "Checking the signature…",
        "click_to_update": "You have {version}. Click to update.",
        "daily": "Daily",
        "dock": "Keep in Dock",
        "dock_restart": "Restart Dock",
        "dock_restart_text": "To change this, macOS has to restart the Dock. Your screen and the menu bar will blink for a moment.",
        "dock_restart_title": "Restart the Dock?",
        "download": "Download",
        "download_failed": "The download failed.",
        "downloading": "Downloading version {version}…",
        "install_now": "Install version {version} now",
        "installed": "Version {version} is installed.",
        "installing": "Installing…",
        "language": "Language",
        "later": "Later",
        "login": "Launch at login",
        "never": "Never",
        "newest": "BeeHan Brightness {version} is currently the newest version available.",
        "not_signed": "The download isn’t signed by Zolfer Figueiredo.",
        "now_using": "You’re now using BeeHan Brightness {version}, the newest version available.",
        "ok": "OK",
        "quit": "Quit BeeHan Brightness",
        "reopen": "Reopen",
        "reopen_failed": "Couldn’t reopen: {error} Quit and open it yourself.",
        "tool_failed": "{tool} failed ({code}).",
        "up_to_date": "You're up to date!",
        "update_available": "Update available!",
        "update_complete": "Update complete!",
        "update_failed": "Couldn’t install the update",
        "update_now": "Update Now",
        "update_question": "You have {version}. Update now?",
        "updating_to": "Updating BeeHan Brightness to {version}",
        "version": "Version {version}",
        "website": "Website",
        "weekly": "Weekly",
        "wrong_download": "The download isn’t BeeHan Brightness {version}.",
    ]
}
