// Español. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let es: [String: String] = [
        "about": "Acerca de BeeHan Brightness",
        "access": "Permitir acceso de Accesibilidad…",
        "applications_only": "BeeHan Brightness solo se actualiza cuando se ejecuta desde la carpeta Aplicaciones.",
        "auto": "Buscar automáticamente",
        "available": "BeeHan Brightness {version} está disponible",
        "by": "Por",
        "cancel": "Cancelar",
        "check": "Buscar actualizaciones…",
        "check_connection": "Comprueba tu conexión e inténtalo de nuevo.",
        "check_failed": "No se pudieron buscar actualizaciones",
        "checking_signature": "Comprobando la firma…",
        "click_to_update": "Tienes la {version}. Haz clic para actualizar.",
        "daily": "Cada día",
        "dock": "Mantener en el Dock",
        "download": "Descargar",
        "download_failed": "La descarga falló.",
        "downloading": "Descargando la versión {version}…",
        "install_now": "Instalar la versión {version} ahora",
        "installed": "La versión {version} está instalada.",
        "installing": "Instalando…",
        "language": "Idioma",
        "later": "Más tarde",
        "login": "Abrir al iniciar sesión",
        "never": "Nunca",
        "newest": "BeeHan Brightness {version} es la versión más reciente disponible.",
        "not_signed": "La descarga no está firmada por Zolfer Figueiredo.",
        "now_using": "Ahora usas BeeHan Brightness {version}, la versión más reciente disponible.",
        "ok": "OK",
        "quit": "Salir de BeeHan Brightness",
        "reopen": "Volver a abrir",
        "reopen_failed": "No se pudo volver a abrir: {error} Sal de la app y ábrela tú.",
        "tool_failed": "{tool} falló ({code}).",
        "up_to_date": "¡Estás al día!",
        "update_available": "¡Actualización disponible!",
        "update_complete": "¡Actualización completada!",
        "update_failed": "No se pudo instalar la actualización",
        "update_now": "Instalar ahora",
        "update_question": "Tienes la {version}. ¿Actualizar ahora?",
        "updating_to": "Actualizando BeeHan Brightness a {version}",
        "version": "Versión {version}",
        "website": "Sitio web",
        "weekly": "Cada semana",
        "wrong_download": "La descarga no es BeeHan Brightness {version}.",
    ]
}
