// Français. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let fr: [String: String] = [
        "about": "À propos de BeeHan Brightness",
        "access": "Autoriser l’accès Accessibilité…",
        "applications_only": "BeeHan Brightness ne se met à jour que lorsqu’il est lancé depuis le dossier Applications.",
        "auto": "Vérifier automatiquement",
        "available": "BeeHan Brightness {version} est disponible",
        "by": "Par",
        "cancel": "Annuler",
        "check": "Rechercher les mises à jour…",
        "check_connection": "Vérifiez votre connexion et réessayez.",
        "check_failed": "Impossible de rechercher les mises à jour",
        "checking_signature": "Vérification de la signature…",
        "click_to_update": "Vous avez la {version}. Cliquez pour mettre à jour.",
        "daily": "Chaque jour",
        "dock": "Garder dans le Dock",
        "download": "Télécharger",
        "download_failed": "Le téléchargement a échoué.",
        "downloading": "Téléchargement de la version {version}…",
        "install_now": "Installer la version {version} maintenant",
        "installed": "La version {version} est installée.",
        "installing": "Installation…",
        "language": "Langue",
        "later": "Plus tard",
        "login": "Ouvrir à la connexion",
        "never": "Jamais",
        "newest": "BeeHan Brightness {version} est la version la plus récente.",
        "not_signed": "Le téléchargement n’est pas signé par Zolfer Figueiredo.",
        "now_using": "Vous utilisez maintenant BeeHan Brightness {version}, la version la plus récente.",
        "ok": "OK",
        "quit": "Quitter BeeHan Brightness",
        "reopen": "Rouvrir",
        "reopen_failed": "Impossible de rouvrir : {error} Quittez l’app et ouvrez-la vous-même.",
        "tool_failed": "{tool} a échoué ({code}).",
        "up_to_date": "Vous êtes à jour !",
        "update_available": "Mise à jour disponible !",
        "update_complete": "Mise à jour terminée !",
        "update_failed": "Impossible d’installer la mise à jour",
        "update_now": "Mettre à jour",
        "update_question": "Vous avez la {version}. Mettre à jour maintenant ?",
        "updating_to": "Mise à jour de BeeHan Brightness vers {version}",
        "version": "Version {version}",
        "website": "Site web",
        "weekly": "Chaque semaine",
        "wrong_download": "Le téléchargement n’est pas BeeHan Brightness {version}.",
    ]
}
