// Italiano. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let it: [String: String] = [
        "about": "Informazioni su BeeHan Brightness",
        "access": "Consenti l’accesso ad Accessibilità…",
        "applications_only": "BeeHan Brightness si aggiorna da solo soltanto se viene eseguito dalla cartella Applicazioni.",
        "auto": "Cerca automaticamente",
        "available": "BeeHan Brightness {version} è disponibile",
        "by": "Di",
        "cancel": "Annulla",
        "check": "Cerca aggiornamenti…",
        "check_connection": "Controlla la connessione e riprova.",
        "check_failed": "Impossibile cercare aggiornamenti",
        "checking_signature": "Verifica della firma…",
        "click_to_update": "Hai la {version}. Fai clic per aggiornare.",
        "daily": "Ogni giorno",
        "dock": "Mantieni nel Dock",
        "dock_restart": "Riavvia il Dock",
        "dock_restart_text": "Per cambiarlo, macOS deve riavviare il Dock. Lo schermo e la barra dei menu lampeggeranno per un attimo.",
        "dock_restart_title": "Riavviare il Dock?",
        "download": "Scarica",
        "download_failed": "Download non riuscito.",
        "downloading": "Download della versione {version}…",
        "install_now": "Installa ora la versione {version}",
        "installed": "La versione {version} è installata.",
        "installing": "Installazione…",
        "language": "Lingua",
        "later": "Più tardi",
        "login": "Apri all’accesso",
        "never": "Mai",
        "newest": "BeeHan Brightness {version} è la versione più recente disponibile.",
        "not_signed": "Il download non è firmato da Zolfer Figueiredo.",
        "now_using": "Ora stai usando BeeHan Brightness {version}, la versione più recente disponibile.",
        "ok": "OK",
        "quit": "Esci da BeeHan Brightness",
        "reopen": "Riapri",
        "reopen_failed": "Impossibile riaprire: {error} Esci dall’app e riaprila tu.",
        "tool_failed": "{tool} non riuscito ({code}).",
        "up_to_date": "Hai già l’ultima versione!",
        "update_available": "Aggiornamento disponibile!",
        "update_complete": "Aggiornamento completato!",
        "update_failed": "Impossibile installare l’aggiornamento",
        "update_now": "Installa ora",
        "update_question": "Hai la {version}. Aggiornare ora?",
        "updating_to": "Aggiornamento di BeeHan Brightness alla {version}",
        "version": "Versione {version}",
        "website": "Sito web",
        "weekly": "Ogni settimana",
        "wrong_download": "Il download non è BeeHan Brightness {version}.",
    ]
}
