// 日本語. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let ja: [String: String] = [
        "about": "BeeHan Brightness について",
        "access": "アクセシビリティのアクセスを許可…",
        "applications_only": "BeeHan Brightness は「アプリケーション」フォルダから実行しているときだけ自動でアップデートします。",
        "auto": "自動で確認",
        "available": "BeeHan Brightness {version} が利用できます",
        "by": "制作:",
        "cancel": "キャンセル",
        "check": "アップデートを確認…",
        "check_connection": "接続を確認して、もう一度お試しください。",
        "check_failed": "アップデートを確認できませんでした",
        "checking_signature": "署名を確認中…",
        "click_to_update": "現在は {version} です。クリックしてアップデート。",
        "daily": "毎日",
        "dock": "Dock に残す",
        "download": "ダウンロード",
        "download_failed": "ダウンロードに失敗しました。",
        "downloading": "バージョン {version} をダウンロード中…",
        "install_now": "バージョン {version} を今すぐインストール",
        "installed": "バージョン {version} をインストールしました。",
        "installing": "インストール中…",
        "language": "言語",
        "later": "あとで",
        "login": "ログイン時に起動",
        "never": "しない",
        "newest": "BeeHan Brightness {version} は現在入手できる最新バージョンです。",
        "not_signed": "ダウンロードしたファイルには Zolfer Figueiredo の署名がありません。",
        "now_using": "BeeHan Brightness {version} を使用中です。現在入手できる最新バージョンです。",
        "ok": "OK",
        "quit": "BeeHan Brightness を終了",
        "reopen": "開き直す",
        "reopen_failed": "開き直せませんでした: {error} アプリを終了して、自分で開いてください。",
        "tool_failed": "{tool} が失敗しました（{code}）。",
        "up_to_date": "最新の状態です",
        "update_available": "アップデートがあります",
        "update_complete": "アップデート完了",
        "update_failed": "アップデートをインストールできませんでした",
        "update_now": "今すぐアップデート",
        "update_question": "現在は {version} です。今すぐアップデートしますか？",
        "updating_to": "BeeHan Brightness を {version} にアップデート中",
        "version": "バージョン {version}",
        "website": "Web サイト",
        "weekly": "毎週",
        "wrong_download": "ダウンロードしたファイルは BeeHan Brightness {version} ではありません。",
    ]
}
