// 한국어. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let ko: [String: String] = [
        "about": "BeeHan Brightness에 관하여",
        "access": "손쉬운 사용 접근 허용…",
        "applications_only": "BeeHan Brightness은(는) 응용 프로그램 폴더에서 실행할 때만 스스로 업데이트합니다.",
        "auto": "자동으로 확인",
        "available": "BeeHan Brightness {version} 사용 가능",
        "by": "제작:",
        "cancel": "취소",
        "check": "업데이트 확인…",
        "check_connection": "연결을 확인하고 다시 시도하세요.",
        "check_failed": "업데이트를 확인할 수 없음",
        "checking_signature": "서명 확인 중…",
        "click_to_update": "현재 {version}입니다. 클릭하여 업데이트하세요.",
        "daily": "매일",
        "dock": "Dock에 유지",
        "dock_restart": "Dock 재시동",
        "dock_restart_text": "이를 변경하려면 macOS가 Dock을 재시동해야 합니다. 화면과 메뉴 막대가 잠깐 깜박입니다.",
        "dock_restart_title": "Dock을 재시동할까요?",
        "download": "다운로드",
        "download_failed": "다운로드에 실패했습니다.",
        "downloading": "버전 {version} 다운로드 중…",
        "install_now": "지금 버전 {version} 설치",
        "installed": "버전 {version}이(가) 설치되었습니다.",
        "installing": "설치 중…",
        "language": "언어",
        "later": "나중에",
        "login": "로그인 시 실행",
        "never": "안 함",
        "newest": "BeeHan Brightness {version}은(는) 현재 사용 가능한 최신 버전입니다.",
        "not_signed": "다운로드한 파일에 Zolfer Figueiredo의 서명이 없습니다.",
        "now_using": "이제 BeeHan Brightness {version}을(를) 사용 중입니다. 현재 사용 가능한 최신 버전입니다.",
        "ok": "확인",
        "quit": "BeeHan Brightness 종료",
        "reopen": "다시 열기",
        "reopen_failed": "다시 열 수 없음: {error} 앱을 종료한 후 직접 여세요.",
        "tool_failed": "{tool} 실패({code}).",
        "up_to_date": "최신 버전입니다!",
        "update_available": "업데이트가 있습니다!",
        "update_complete": "업데이트 완료!",
        "update_failed": "업데이트를 설치할 수 없음",
        "update_now": "지금 업데이트",
        "update_question": "현재 {version}입니다. 지금 업데이트할까요?",
        "updating_to": "BeeHan Brightness을(를) {version}(으)로 업데이트 중",
        "version": "버전 {version}",
        "website": "웹사이트",
        "weekly": "매주",
        "wrong_download": "다운로드한 파일이 BeeHan Brightness {version}이(가) 아닙니다.",
    ]
}
