// Polski. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let pl: [String: String] = [
        "about": "O BeeHan Brightness",
        "access": "Zezwól na dostęp w Dostępności…",
        "applications_only": "BeeHan Brightness uaktualnia się sam tylko wtedy, gdy działa z folderu Aplikacje.",
        "auto": "Sprawdzaj automatycznie",
        "available": "Dostępna jest wersja BeeHan Brightness {version}",
        "by": "Autor:",
        "cancel": "Anuluj",
        "check": "Sprawdź uaktualnienia…",
        "check_connection": "Sprawdź połączenie i spróbuj ponownie.",
        "check_failed": "Nie udało się sprawdzić uaktualnień",
        "checking_signature": "Sprawdzanie podpisu…",
        "click_to_update": "Masz wersję {version}. Kliknij, aby uaktualnić.",
        "daily": "Codziennie",
        "dock": "Zostaw w Docku",
        "dock_restart": "Uruchom ponownie Dock",
        "dock_restart_text": "Aby to zmienić, macOS musi ponownie uruchomić Dock. Ekran i pasek menu na chwilę mrugną.",
        "dock_restart_title": "Uruchomić ponownie Dock?",
        "download": "Pobierz",
        "download_failed": "Pobieranie nie powiodło się.",
        "downloading": "Pobieranie wersji {version}…",
        "install_now": "Zainstaluj teraz wersję {version}",
        "installed": "Wersja {version} jest zainstalowana.",
        "installing": "Instalowanie…",
        "language": "Język",
        "later": "Później",
        "login": "Uruchamiaj przy logowaniu",
        "never": "Nigdy",
        "newest": "BeeHan Brightness {version} to obecnie najnowsza dostępna wersja.",
        "not_signed": "Pobrany plik nie jest podpisany przez Zolfer Figueiredo.",
        "now_using": "Używasz teraz BeeHan Brightness {version}, najnowszej dostępnej wersji.",
        "ok": "OK",
        "quit": "Zakończ BeeHan Brightness",
        "reopen": "Otwórz ponownie",
        "reopen_failed": "Nie udało się otworzyć ponownie: {error} Zakończ aplikację i otwórz ją samodzielnie.",
        "tool_failed": "{tool}: niepowodzenie ({code}).",
        "up_to_date": "Masz najnowszą wersję!",
        "update_available": "Dostępne uaktualnienie!",
        "update_complete": "Uaktualnienie zakończone!",
        "update_failed": "Nie udało się zainstalować uaktualnienia",
        "update_now": "Uaktualnij teraz",
        "update_question": "Masz wersję {version}. Uaktualnić teraz?",
        "updating_to": "Uaktualnianie BeeHan Brightness do {version}",
        "version": "Wersja {version}",
        "website": "Strona",
        "weekly": "Co tydzień",
        "wrong_download": "Pobrany plik to nie BeeHan Brightness {version}.",
    ]
}
