// Português. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let pt: [String: String] = [
        "about": "Sobre o BeeHan Brightness",
        "access": "Permitir acesso de Acessibilidade…",
        "applications_only": "O BeeHan Brightness só se atualiza quando é executado da pasta Aplicativos.",
        "auto": "Verificar automaticamente",
        "available": "BeeHan Brightness {version} está disponível",
        "by": "Por",
        "cancel": "Cancelar",
        "check": "Buscar atualizações…",
        "check_connection": "Verifique sua conexão e tente de novo.",
        "check_failed": "Não foi possível buscar atualizações",
        "checking_signature": "Verificando a assinatura…",
        "click_to_update": "Você tem a {version}. Clique para atualizar.",
        "daily": "Diariamente",
        "dock": "Manter no Dock",
        "dock_restart": "Reiniciar o Dock",
        "dock_restart_text": "Para mudar isso, o macOS precisa reiniciar o Dock. A tela e a barra de menus vão piscar por um instante.",
        "dock_restart_title": "Reiniciar o Dock?",
        "download": "Baixar",
        "download_failed": "O download falhou.",
        "downloading": "Baixando a versão {version}…",
        "install_now": "Instalar a versão {version} agora",
        "installed": "A versão {version} está instalada.",
        "installing": "Instalando…",
        "language": "Idioma",
        "later": "Depois",
        "login": "Abrir ao iniciar sessão",
        "never": "Nunca",
        "newest": "BeeHan Brightness {version} é a versão mais recente disponível.",
        "not_signed": "O download não está assinado por Zolfer Figueiredo.",
        "now_using": "Agora você está usando o BeeHan Brightness {version}, a versão mais recente disponível.",
        "ok": "OK",
        "quit": "Encerrar BeeHan Brightness",
        "reopen": "Reabrir",
        "reopen_failed": "Não foi possível reabrir: {error} Encerre o app e abra-o você mesmo.",
        "tool_failed": "{tool} falhou ({code}).",
        "up_to_date": "Você está atualizado!",
        "update_available": "Atualização disponível!",
        "update_complete": "Atualização concluída!",
        "update_failed": "Não foi possível instalar a atualização",
        "update_now": "Instalar agora",
        "update_question": "Você tem a {version}. Atualizar agora?",
        "updating_to": "Atualizando BeeHan Brightness para {version}",
        "version": "Versão {version}",
        "website": "Site",
        "weekly": "Semanalmente",
        "wrong_download": "O download não é o BeeHan Brightness {version}.",
    ]
}
