// Русский. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let ru: [String: String] = [
        "about": "О программе BeeHan Brightness",
        "access": "Разрешить доступ в «Универсальном доступе»…",
        "applications_only": "BeeHan Brightness обновляется сам, только если запущен из папки «Программы».",
        "auto": "Проверять автоматически",
        "available": "Доступна версия BeeHan Brightness {version}",
        "by": "Автор:",
        "cancel": "Отменить",
        "check": "Проверить обновления…",
        "check_connection": "Проверьте подключение и повторите попытку.",
        "check_failed": "Не удалось проверить обновления",
        "checking_signature": "Проверка подписи…",
        "click_to_update": "У вас {version}. Нажмите, чтобы обновить.",
        "daily": "Ежедневно",
        "dock": "Оставить в Dock",
        "dock_restart": "Перезапустить Dock",
        "dock_restart_text": "Для этого macOS нужно перезапустить Dock. Экран и строка меню на мгновение мигнут.",
        "dock_restart_title": "Перезапустить Dock?",
        "download": "Скачать",
        "download_failed": "Не удалось загрузить.",
        "downloading": "Загрузка версии {version}…",
        "install_now": "Установить версию {version} сейчас",
        "installed": "Версия {version} установлена.",
        "installing": "Установка…",
        "language": "Язык",
        "later": "Позже",
        "login": "Запускать при входе",
        "never": "Никогда",
        "newest": "BeeHan Brightness {version}: это самая новая доступная версия.",
        "not_signed": "Загрузка не подписана Zolfer Figueiredo.",
        "now_using": "Теперь вы используете BeeHan Brightness {version}, самую новую доступную версию.",
        "ok": "OK",
        "quit": "Завершить BeeHan Brightness",
        "reopen": "Открыть снова",
        "reopen_failed": "Не удалось открыть снова: {error} Завершите приложение и откройте его сами.",
        "tool_failed": "{tool}: сбой ({code}).",
        "up_to_date": "У вас последняя версия!",
        "update_available": "Доступно обновление!",
        "update_complete": "Обновление завершено!",
        "update_failed": "Не удалось установить обновление",
        "update_now": "Установить сейчас",
        "update_question": "У вас {version}. Обновить сейчас?",
        "updating_to": "Обновление BeeHan Brightness до {version}",
        "version": "Версия {version}",
        "website": "Сайт",
        "weekly": "Еженедельно",
        "wrong_download": "Загружен не BeeHan Brightness {version}.",
    ]
}
