// Українська. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let uk: [String: String] = [
        "about": "Про BeeHan Brightness",
        "access": "Дозволити доступ у «Доступності»…",
        "applications_only": "BeeHan Brightness оновлюється сам, лише коли запущений із папки «Програми».",
        "auto": "Перевіряти автоматично",
        "available": "Доступна версія BeeHan Brightness {version}",
        "by": "Автор:",
        "cancel": "Скасувати",
        "check": "Перевірити оновлення…",
        "check_connection": "Перевірте з’єднання та спробуйте ще раз.",
        "check_failed": "Не вдалося перевірити оновлення",
        "checking_signature": "Перевірка підпису…",
        "click_to_update": "У вас {version}. Натисніть, щоб оновити.",
        "daily": "Щодня",
        "dock": "Залишити в Dock",
        "download": "Завантажити",
        "download_failed": "Не вдалося завантажити.",
        "downloading": "Завантаження версії {version}…",
        "install_now": "Встановити версію {version} зараз",
        "installed": "Версію {version} встановлено.",
        "installing": "Встановлення…",
        "language": "Мова",
        "later": "Пізніше",
        "login": "Запускати під час входу",
        "never": "Ніколи",
        "newest": "BeeHan Brightness {version}: це найновіша доступна версія.",
        "not_signed": "Завантаження не підписано Zolfer Figueiredo.",
        "now_using": "Тепер ви використовуєте BeeHan Brightness {version}, найновішу доступну версію.",
        "ok": "OK",
        "quit": "Завершити BeeHan Brightness",
        "reopen": "Відкрити знову",
        "reopen_failed": "Не вдалося відкрити знову: {error} Завершіть програму й відкрийте її самі.",
        "tool_failed": "{tool}: збій ({code}).",
        "up_to_date": "У вас найновіша версія!",
        "update_available": "Доступне оновлення!",
        "update_complete": "Оновлення завершено!",
        "update_failed": "Не вдалося встановити оновлення",
        "update_now": "Встановити зараз",
        "update_question": "У вас {version}. Оновити зараз?",
        "updating_to": "Оновлення BeeHan Brightness до {version}",
        "version": "Версія {version}",
        "website": "Сайт",
        "weekly": "Щотижня",
        "wrong_download": "Завантажено не BeeHan Brightness {version}.",
    ]
}
