// 中文. Most of these are the strings ClaudioStat and its website use.
extension Strings {
    static let zh: [String: String] = [
        "about": "关于 BeeHan Brightness",
        "access": "允许辅助功能权限…",
        "applications_only": "BeeHan Brightness 仅在从“应用程序”文件夹运行时才会自行更新。",
        "auto": "自动检查",
        "available": "BeeHan Brightness {version} 已可用",
        "by": "作者:",
        "cancel": "取消",
        "check": "检查更新…",
        "check_connection": "请检查网络连接后重试。",
        "check_failed": "无法检查更新",
        "checking_signature": "正在检查签名…",
        "click_to_update": "当前版本为 {version}。点按即可更新。",
        "daily": "每天",
        "dock": "保留在 Dock 中",
        "download": "下载",
        "download_failed": "下载失败。",
        "downloading": "正在下载版本 {version}…",
        "install_now": "立即安装版本 {version}",
        "installed": "版本 {version} 已安装。",
        "installing": "正在安装…",
        "language": "语言",
        "later": "稍后",
        "login": "登录时启动",
        "never": "从不",
        "newest": "BeeHan Brightness {version} 是目前最新的版本。",
        "not_signed": "下载的文件不是由 Zolfer Figueiredo 签名的。",
        "now_using": "你现在使用的是 BeeHan Brightness {version}，这是目前最新的版本。",
        "ok": "好",
        "quit": "退出 BeeHan Brightness",
        "reopen": "重新打开",
        "reopen_failed": "无法重新打开：{error} 请退出应用后自行打开。",
        "tool_failed": "{tool} 失败（{code}）。",
        "up_to_date": "已是最新版本！",
        "update_available": "有可用更新！",
        "update_complete": "更新完成！",
        "update_failed": "无法安装更新",
        "update_now": "立即更新",
        "update_question": "当前版本为 {version}。现在更新吗？",
        "updating_to": "正在将 BeeHan Brightness 更新到 {version}",
        "version": "版本 {version}",
        "website": "网站",
        "weekly": "每周",
        "wrong_download": "下载的文件不是 BeeHan Brightness {version}。",
    ]
}
